$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: uv run scripts/train.py pi0_fast_libero --exp-name=${{inputs.experiment_name}} --overwrite --assets-base-dir ${{outputs.ASSETS_BASE}} --checkpoint-base-dir ${{outputs.MODEL_CHECKPOINTS}} --num-workers 8 --fsdp-devices 2 --batch-size 64
environment: azureml:libero-env:latest
inputs:
  config_name: pi0_fast_libero
  experiment_name: dummy_exp
outputs:
  MODEL_CHECKPOINTS:
    type: uri_folder
    path: azureml://datastores/libero/paths/finetuned_model/
  LEROBOT_HOME:
    type: uri_folder
    path: azureml://datastores/libero/paths/pi0_fast_libero
  ASSETS_BASE:
    type: uri_folder
    path: azureml://datastores/libero/paths/
environment_variables:
  LEROBOT_HOME: ${{outputs.LEROBOT_HOME}}
  MODEL_CHECKPOINTS: ${{outputs.MODEL_CHECKPOINTS}}
  XLA_PYTHON_CLIENT_PREALLOCATE: "false"
  XLA_PYTHON_CLIENT_MEM_FRACTION: ".95"
  XLA_PYTHON_CLIENT_ALLOCATOR: "platform"
display_name: p0_libero_finetune
experiment_name: p0_libero_finetune
compute: dummy_compute
code: ..